name: Rclone for GoogleDrive

on:
  release:
    types: [published]
  schedule:
    - cron: 0 */6 * * *

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "copy --ignore-existing --stats 15s --bwlimit 6M gdrive_edu:/2019年程序员数学（基础+进阶） team_tw:/cxysx"
