name: Rclone for GoogleDrive

on:
  release:
    types: [published]
  schedule:
    - cron: 0/5 * * * *

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: "copy --ignore-existing --stats 15s --bwlimit 10M gdrive_edu:/started team_tw:/cxysx"
